#!/usr/bin/env python3
"""Render a build estimate as Markdown and PDF.

Author: Dewain Robinson

    python render_report.py estimate.json -o report --format both

PDF generation failing must never lose the estimate: the Markdown is written
first, and a missing Playwright or Chromium is reported with its remediation
rather than raised.
"""

__author__ = "Dewain Robinson"

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import copilot_credits  # noqa: E402
import github_copilot  # noqa: E402
import target_platform as tp  # noqa: E402
import licensing  # noqa: E402
import rates  # noqa: E402

NOT_A_COMPARISON = """> **This is not a platform comparison tool.** It reports one chosen build
> platform and one chosen target, each in its own meter. Platform decisions are
> not made on cost alone — capability, existing skills, governance, integration,
> and support all matter more than a build-time figure — and using this report
> to pick a platform would be using it for something it was not designed to
> answer."""

AUTHOR = "Dewain Robinson"

DISCLAIMER = """> ### SAMPLE — BUILD ESTIMATE ONLY, NOT A QUOTE
>
> This document is generated by a **sample estimator** published as a
> demonstration of *how* an organization could build one. It is not a quote, a
> bid, a budget authority, or a commitment of any kind.
>
> **It estimates the work of building only — never the cost of running what
> gets built.** Runtime, end-user licences, infrastructure, and human labour
> are all outside its scope and are not represented in any figure below.
>
> **The figures are estimates and will be wrong.** They are derived from
> historical consumption patterns that may not resemble the work being
> estimated. Observed cost for comparable work in the calibration data spans
> more than 100x between the cheapest and most expensive instances. Treat the
> range as the estimate; treat the point figure as the midpoint of a guess.
>
> **Before any real budgeting use, this estimator must be modified for your
> organization** — recalibrated against your own usage history, repriced
> against your contracted rates rather than list price, and adjusted for your
> own delivery patterns, model choices, and review overhead.
>
> Rates verified {rate_date} and change without notice.
> Calibration source: `{calibration_source}` · Generated {timestamp}"""

FOOTER = ("SAMPLE — build estimate only, not a quote. Excludes runtime cost. "
          "Modify for your organization before budgeting use.")

SCOPE_TABLE = """| Out of scope | Where to go instead |
| --- | --- |
| Runtime / operational cost of what gets built | [Copilot Studio agent usage estimator](https://microsoft.github.io/copilot-studio-estimator/) |
| End-user seat licences (M365 Copilot, Power Platform) | Your licensing/procurement process |
| Infrastructure, hosting, storage, egress | Your cloud cost tooling |
| Human labour — PM, design, QA time | Your delivery estimation process |
| Ongoing maintenance and support after delivery | A run cost, not a build cost |"""


def money(value):
    return "$" + format(round(float(value), 2), ",.2f")


def build_header(result):
    """Front matter, title, disclaimer, and the stack/scope banners."""
    out = []
    out.append("---")
    out.append("title: Build Work Estimate — %s" % result["project"])
    out.append("author: %s" % AUTHOR)
    out.append("build_platform: %s" % result["build_platform"])
    out.append("target_platform: %s" % result["target_platform"])
    out.append("estimate_id: %s" % result["estimate_id"])
    out.append("generated: %s" % result["generated"])
    out.append("---")
    out.append("")
    out.append("# Build Work Estimate — %s" % result["project"])
    out.append("")
    out.append("**Author:** %s · **Estimate id:** `%s` · **Generated:** %s"
               % (AUTHOR, result["estimate_id"], result["generated"]))
    out.append("")
    out.append(DISCLAIMER.format(
        rate_date=rates.ANTHROPIC_VERIFIED,
        calibration_source=(result.get("profile") or {}).get(
            "source", "not applicable"),
        timestamp=result["generated"]))
    out.append("")
    return out


def build_context(result):
    """Framing that follows the summary: what the platforms mean, and scope."""
    out = []
    out.append("## Platforms")
    out.append("")
    out.append("| | Platform | Metered in |")
    out.append("| --- | --- | --- |")
    out.append("| **Built with** | %s | %s |"
               % (result["build_platform_label"], result["build_currency"]))
    out.append("| **Built on** | %s | %s |"
               % (result["target_platform_label"], result["target_currency"]))
    out.append("")
    out.append("> These are different questions and different meters, and the "
               "same project spends\n> on **both**. The building happens in a "
               "coding agent authoring the agent\n> definition; the target "
               "platform is where it is deployed, previewed, evaluated\n> and "
               "validated. Copilot Studio is a destination, not a build tool.")
    out.append("")
    out.append(NOT_A_COMPARISON)
    out.append("")
    out.append("## Scope — this estimates the build, not the run")
    out.append("")
    out.append("This figure covers the work of **building** the thing. It does "
               "not\ncover operating it afterwards.")
    out.append("")
    out.append(SCOPE_TABLE)
    out.append("")
    return out


def _build_totals(result):
    """Low / likely / high / with-reserve for the build side, in USD."""
    build, detail = result.get("build"), result.get("build_detail")
    reserve = result["reserve_percent"]
    if build:
        return {
            "currency": "USD",
            "low": build["low"], "likely": build["base"], "high": build["high"],
            "with_reserve": build["budget_ask"],
            "usd_low": build["low"], "usd_likely": build["base"],
            "usd_high": build["high"], "usd_with_reserve": build["budget_ask"],
            "notional": (build.get("licensing") or {}).get("model") == "seat",
        }
    detail = detail or {}
    units = detail.get("total_units", 0) or 0
    rate = rates.DOLLARS_PER_GITHUB_AI_CREDIT
    with_reserve = detail.get("budget_units", units)
    sized = detail.get("sized_from_items")
    low = detail.get("low_units", units)
    high = detail.get("high_units", units)
    return {
        "currency": "GitHub AI Credits",
        "low": low, "likely": units, "high": high,
        "with_reserve": with_reserve,
        "usd_low": round(low * rate, 2), "usd_likely": round(units * rate, 2),
        "usd_high": round(high * rate, 2),
        "usd_with_reserve": round(with_reserve * rate, 2),
        "notional": (result.get("licensing") or {}).get("model") == "seat",
        "no_range": not sized,
        "sized_from_items": bool(sized),
    }


def _target_totals(result):
    """Low / likely / high / with-reserve summed across targets, in USD."""
    low = likely = high = with_reserve = 0.0
    credits_low = credits_likely = credits_high = credits_reserve = 0.0
    for target in result["targets"]:
        if target["target"] == "azure":
            low += target["total_dollars"]
            likely += target["total_dollars"]
            high += target["total_dollars"]
            with_reserve += target["budget_dollars"]
            continue
        span = target.get("range") or {}
        credits_low += span.get("low_credits", target["total_credits"])
        credits_likely += target["total_credits"]
        credits_high += span.get("high_credits", target["total_credits"])
        credits_reserve += target["budget_credits"]
        low += span.get("low_dollars", target["total_dollars"])
        likely += target["total_dollars"]
        high += span.get("high_dollars", target["total_dollars"])
        with_reserve += target["budget_dollars"]
    return {
        "credits_low": credits_low, "credits_likely": credits_likely,
        "credits_high": credits_high, "credits_with_reserve": credits_reserve,
        "usd_low": round(low, 2), "usd_likely": round(likely, 2),
        "usd_high": round(high, 2), "usd_with_reserve": round(with_reserve, 2),
    }


def build_summary(result):
    """The section a reader looks at first: inputs, then the four numbers."""
    out = ["## Estimate summary", ""]

    # --- what was estimated -------------------------------------------
    licence = (result.get("build") or {}).get("licensing") \
        or result.get("licensing") or {}
    target = result["targets"][0] if result["targets"] else {}
    profile = (result.get("profile") or {})

    out.append("### What was estimated")
    out.append("")
    out.append("| Input | Value |")
    out.append("| --- | --- |")
    out.append("| **Built with** (development tool) | %s — metered in %s |"
               % (result["build_platform_label"], result["build_currency"]))
    out.append("| **Built on** (target environment) | %s — metered in %s |"
               % (result["target_platform_label"], result["target_currency"]))
    if target.get("harness"):
        out.append("| Target harness | `%s` — %s |"
                   % (target["harness"],
                      "bills for build, test and evaluation"
                      if target.get("bills_during_build")
                      else "does not bill for build or test"))
    if licence.get("model") == "seat":
        # Two shapes reach here. licensing.attribute() stores the TOTAL across
        # seats; licensing.normalise() stores the PER-SEAT figure. Dividing
        # both misreports one of them, so discriminate explicitly.
        seats = max(1, licence.get("seats", 1))
        months = licence.get("duration_months", 1) or 1
        # licensing.attribute() stores the TOTAL over the build and the true
        # monthly rate separately; licensing.normalise() stores only the rate.
        # Labelling the total as "per month" overstated it by the duration.
        rate = licence.get("seat_rate_monthly")
        if rate is None:
            rate = licence.get("seat_monthly_cost", 0)
        total = rate * seats * months
        out.append("| Licensing | Seat — %s, $%s/month x %d seat%s x %s month%s "
                   "= **$%s** over the build |"
                   % (licence.get("plan") or "unspecified",
                      format(rate, ",.2f"), seats, "" if seats == 1 else "s",
                      format(months, ",g"), "" if months == 1 else "s",
                      format(total, ",.2f")))
    elif licence.get("model"):
        out.append("| Licensing | Consumption — every unit bills |")
    out.append("| Evaluation cycles planned | %d |" % result["eval_cycles"])
    out.append("| Contingency reserve | %.0f%% |" % result["reserve_percent"])
    if profile.get("source") == "measured" and \
            profile.get("sized_from_claude_calibration"):
        out.append("| Work sizing | Turn counts from measured Claude Code "
                   "calibration (%d session%s), used as a work-size proxy |"
                   % (profile.get("sessions", 0),
                      "" if profile.get("sessions") == 1 else "s"))
    elif profile.get("source") == "measured":
        out.append("| Calibration | Measured, %d local session%s |"
                   % (profile.get("sessions", 0),
                      "" if profile.get("sessions") == 1 else "s"))
    elif profile.get("source") == "not applicable":
        out.append("| Calibration | Not applicable — the build platform is "
                   "not metered from local session history |")
    elif profile.get("source"):
        out.append("| Calibration | %s |" % profile["source"])
    out.append("")

    # --- the four numbers ---------------------------------------------
    build = _build_totals(result)
    tgt = _target_totals(result)
    combined = dict(
        (k, round(build["usd_" + k] + tgt["usd_" + k], 2))
        for k in ("low", "likely", "high", "with_reserve"))

    # Show the credits column whenever a Copilot Studio target is in scope,
    # even when it bills zero. Hiding a zero reads as "no target estimated"
    # rather than "the target costs nothing on this harness".
    has_credits = tgt["credits_likely"] > 0 or any(
        target["target"] == "copilot-studio" for target in result["targets"])
    out.append("### Totals")
    out.append("")
    header = "| | Build — %s |" % build["currency"]
    divider = "| --- | ---: |"
    if has_credits:
        header += " Target — Copilot Credits |"
        divider += " ---: |"
    header += " **Combined (USD)** |"
    divider += " ---: |"
    out.append(header)
    out.append(divider)

    def row(label, bkey, ckey, ukey, bold=False):
        wrap = (lambda s: "**%s**" % s) if bold else (lambda s: s)
        cells = [wrap(label)]
        cells.append(wrap(money(build[bkey]) if build["currency"] == "USD"
                          else format(build[bkey], ",.0f")))
        if has_credits:
            cells.append(wrap(format(tgt[ckey], ",.0f")))
        cells.append(wrap(money(combined[ukey])))
        return "| " + " | ".join(cells) + " |"

    out.append(row("Low", "low", "credits_low", "low"))
    out.append(row("Likely", "likely", "credits_likely", "likely", bold=True))
    out.append(row("High", "high", "credits_high", "high"))
    out.append(row("Likely + %.0f%% reserve" % result["reserve_percent"],
                   "with_reserve", "credits_with_reserve", "with_reserve",
                   bold=True))
    out.append("")

    out.append("> **Plan for %s. Hold %s including the %.0f%% reserve.**"
               % (money(combined["likely"]), money(combined["with_reserve"]),
                  result["reserve_percent"]))
    out.append("")
    out.append("**Two meters, not two options.** The build and target figures "
               "are spent on the same\nproject over the same period and add "
               "together; they are not alternatives to choose\nbetween.")
    out.append("")

    notes = []
    zero_target = has_credits and tgt["credits_likely"] == 0
    if zero_target:
        notes.append("The target column is **zero because of the harness**, "
                     "not because nothing was estimated. On the standard "
                     "harness, build, preview, test and evaluation in the "
                     "interface are not billed, and agent flow test runs are "
                     "explicitly exempt. See the target section below.")
    if has_credits and not zero_target:
        notes.append("Copilot Credits are converted at $%.2f each so the two "
                     "meters can be shown in one column. They are separate "
                     "budgets drawn on different accounts."
                     % rates.DOLLARS_PER_CREDIT)
    if build.get("notional"):
        notes.append("The build figure is **notional** — on seat licensing no "
                     "additional money is invoiced. See Licensing below for "
                     "the share of the seat this build actually consumes.")
    if build.get("sized_from_items"):
        notes.append("The build side is sized from the same work breakdown "
                     "using turn medians measured on Claude Code. Turn count "
                     "is treated as a property of the work rather than of the "
                     "tool; the price per turn is not. That is an assumption, "
                     "not a measurement of GitHub Copilot.")
    elif build.get("no_range"):
        notes.append("The build side has no measured spread of its own: the "
                     "declared interaction volume is the estimate. Only the "
                     "target side varies here.")
    else:
        notes.append("The build range comes from observed spread in comparable "
                     "work; the target range from running %d to %d evaluation "
                     "cycles instead of %d."
                     % ((result["targets"][0].get("range") or {}).get(
                            "low_cycles", result["eval_cycles"]),
                        (result["targets"][0].get("range") or {}).get(
                            "high_cycles", result["eval_cycles"]),
                        result["eval_cycles"])
                     if result["targets"] else
                     "The build range comes from observed spread in "
                     "comparable work.")
    for note in notes:
        out.append("- %s" % note)
    out.append("")
    out.append("Everything below explains how each of these figures was "
               "reached.")
    out.append("")
    return out


def build_plan_markdown(result):
    """Combined report: build platform + target platform, both meters."""
    out = build_header(result)
    out.extend(build_summary(result))
    out.extend(build_context(result))

    build = result.get("build")
    detail = result.get("build_detail")

    out.append("## The build loop")
    out.append("")
    out.append("```")
    out.append("  %-22s        %s" % (result["build_platform_label"],
                                      result["target_platform_label"]))
    out.append("  %-22s        %s" % ("-" * 22, "-" * 22))
    out.append("  author definition   -->  deploy")
    out.append("                           preview / interactive test  <- human")
    out.append("                           run evaluations")
    out.append("  remediate           <--  evaluations fail")
    out.append("  (repeat)")
    out.append("```")
    out.append("")
    out.append("This estimate plans **%d evaluation cycle%s**. Each cycle after "
               "the first adds\n**%.0f%%** of the original build back as "
               "remediation, giving a build-side multiplier\nof **%.2fx**. An "
               "estimate that prices only the first pass is planning for a "
               "build\nwhere every evaluation passes first time."
               % (result["eval_cycles"],
                  "" if result["eval_cycles"] == 1 else "s",
                  result["remediation_share"] * 100,
                  result["remediation_factor"]))
    out.append("")

    if build:
        out.append("## Build — %s" % result["build_platform_label"])
        out.append("")
        out.append("| | Amount |")
        out.append("| --- | ---: |")
        out.append("| Base estimate (incl. remediation) | %s |"
                   % money(build["base"]))
        out.append("| Reserve (%.0f%%) | %s |"
                   % (build["reserve_percent"], money(build["reserve"])))
        out.append("| **Budget ask** | **%s** |" % money(build["budget_ask"]))
        out.append("| Observed low | %s |" % money(build["low"]))
        out.append("| Observed high | %s |" % money(build["high"]))
        out.append("")
        adequacy = build["adequacy"]
        out.append("### Reserve adequacy")
        out.append("")
        if adequacy["covers_high"]:
            out.append("A **%.0f%%** reserve brings the budget ask to %s, "
                       "which covers the observed high of %s."
                       % (adequacy["reserve_percent"],
                          money(adequacy["budget_ask"]), money(adequacy["high"])))
        else:
            out.append("**The reserve does not cover observed variance.**")
            out.append("")
            out.append("A **%.0f%%** reserve reaches %s. Comparable work has "
                       "reached %s. Full coverage\nwould require **%.0f%%**."
                       % (adequacy["reserve_percent"],
                          money(adequacy["budget_ask"]), money(adequacy["high"]),
                          adequacy["required_percent"]))
        out.append("")
        out.append("| Item | Size | Files | Turns | Estimate | Range | n |")
        out.append("| --- | --- | ---: | ---: | ---: | --- | ---: |")
        for row in build["items"]:
            out.append("| %s | %s%s | %d | %s | %s | %s – %s | %d |"
                       % (row["name"], row["size"],
                          " (brownfield)" if row["brownfield"] else "",
                          row["files"], format(row["turns"], ","),
                          money(row["cost"]), money(row["low"]),
                          money(row["high"]), row["n"]))
        out.append("")
        if build.get("thin_buckets"):
            out.append("> **Thin calibration data** for: %s. Those medians are "
                       "weak." % ", ".join(build["thin_buckets"]))
            out.append("")
        profile = build["profile"]
        out.append("### Calibration basis")
        out.append("")
        if profile["source"] == "measured":
            out.append("Measured from %d local session%s%s."
                       % (profile["sessions"],
                          "" if profile["sessions"] == 1 else "s",
                          (" spanning %s to %s" % tuple(profile["date_range"]))
                          if profile.get("date_range") else ""))
        else:
            out.append("**Published baselines — no local session history was "
                       "found.** This is\nmaterially less reliable than a "
                       "measured profile. Run `calibrate.py` after some\nreal "
                       "work to improve it.")
        out.append("")
        out.append("Cost per agent turn: **%s**, at **list price** — an "
                   "organization on contracted\nrates must substitute its own."
                   % money(profile["cost_per_main_turn"]))
        out.append("")
        if build.get("licensing"):
            out.append(licensing.render_markdown(build["licensing"]))
    elif detail:
        out.append(github_copilot.render_markdown(detail))

    for target in result["targets"]:
        out.append(tp.render_markdown(target))

    out.append("## Known limits")
    out.append("")
    out.append("1. **Build only.** Nothing here is the cost of running the "
               "agent once it is live.")
    out.append("2. **Human validation is a dependency, not a line item.** "
               "Hours are collected to\n   size test volume, never estimated "
               "as labour.")
    out.append("3. **Turn counts are the weakest input**, and thin buckets are "
               "flagged above.")
    out.append("4. **Rates go stale.** Re-verify against the sources cited.")
    out.append("5. **This is a sample.** Modify it for your organization "
               "before budgeting use.")
    out.append("")
    for warning in result.get("warnings") or []:
        out.append("> WARNING: %s" % warning)
    if result.get("warnings"):
        out.append("")
    out.append("## Close the loop")
    out.append("")
    out.append("```")
    out.append("python record_actual.py %s --sessions <session-id> [...]"
               % result["estimate_id"])
    out.append("```")
    out.append("")
    out.append("---")
    out.append("")
    out.append("*%s*" % FOOTER)
    out.append("")
    return "\n".join(out)


def build_stack_markdown(result):
    """Report for a non-Claude-Code stack, in that stack's own currency."""
    out = build_header(result) + build_context(result)
    detail = result["stack_detail"]

    if result["build_stack"] == "copilot-studio":
        out.append(copilot_credits.render_markdown(detail))
    else:
        out.append(github_copilot.render_markdown(detail))

    licence = result.get("licensing") or {}
    if licence.get("model") == licensing.SEAT:
        out.append("## Licensing")
        out.append("")
        out.append("**Seat / allowance-based licensing (%s).** The consumption "
                   "above draws on an\nallowance already paid for. No "
                   "additional money changes hands until the\nallowance is "
                   "exhausted — but the allowance itself was bought, so the "
                   "capacity\nthis build uses up has a real cost."
                   % (licence.get("plan") or "unspecified"))
        out.append("")
        if licence.get("seat_monthly_cost"):
            out.append("Seat cost: **$%s/month** × %d seat%s. Committed to "
                       "other work: **%.0f%%**."
                       % (format(licence["seat_monthly_cost"], ",.2f"),
                          licence.get("seats", 1),
                          "" if licence.get("seats", 1) == 1 else "s",
                          licence.get("other_workload_share", 0) * 100))
            out.append("")
    else:
        out.append("## Licensing")
        out.append("")
        out.append("**Consumption billing.** Every unit consumed is billed, so "
                   "the figures above\nare the expected charge.")
        out.append("")

    out.append("## Known limits")
    out.append("")
    out.append("1. **Build only.** Says nothing about what the built thing "
               "costs to run.")
    out.append("2. **Rates go stale.** Verified %s; re-verify against the "
               "sources above." % rates.COPILOT_VERIFIED)
    out.append("3. **This is a sample.** Modify it for your organization "
               "before budgeting use.")
    out.append("")
    for warning in result.get("warnings") or []:
        out.append("> WARNING: %s" % warning)
    if result.get("warnings"):
        out.append("")
    out.append("## Close the loop")
    out.append("")
    out.append("```")
    out.append("python record_actual.py %s --sessions <session-id> [...]"
               % result["estimate_id"])
    out.append("```")
    out.append("")
    out.append("---")
    out.append("")
    out.append("*%s*" % FOOTER)
    out.append("")
    return "\n".join(out)


def build_markdown(result, credits=None):
    if result.get("targets") is not None:
        return build_plan_markdown(result)
    if result.get("stack_detail") is not None:
        return build_stack_markdown(result)
    p = result["profile"]
    source = p["source"]
    if source == "measured":
        basis = ("Measured from %d local session%s%s."
                 % (p["sessions"], "" if p["sessions"] == 1 else "s",
                    (" spanning %s to %s" % tuple(p["date_range"]))
                    if p.get("date_range") else ""))
    else:
        basis = ("**Published baselines — no local session history was found.** "
                 "This is materially less reliable than a measured profile. "
                 "Run `calibrate.py` after some real work to improve it.")

    out = build_header(result) + build_context(result)
    out.append("## Summary")
    out.append("")
    out.append("| | Amount |")
    out.append("| --- | ---: |")
    out.append("| Base estimate | %s |" % money(result["base"]))
    out.append("| Reserve (%.0f%%) | %s |"
               % (result["reserve_percent"], money(result["reserve"])))
    out.append("| **Budget ask** | **%s** |" % money(result["budget_ask"]))
    out.append("| Observed low | %s |" % money(result["low"]))
    out.append("| Observed high | %s |" % money(result["high"]))
    out.append("")

    a = result["adequacy"]
    out.append("## Reserve adequacy")
    out.append("")
    if a["covers_high"]:
        out.append("A **%.0f%%** reserve brings the budget ask to %s, which "
                   "covers the observed high of %s for comparable work."
                   % (a["reserve_percent"], money(a["budget_ask"]),
                      money(a["high"])))
    else:
        out.append("**The reserve does not cover observed variance.**")
        out.append("")
        out.append("A **%.0f%%** reserve brings the budget ask to %s. "
                   "Comparable work in the\ncalibration data has reached %s. "
                   "Full coverage would require **%.0f%%**."
                   % (a["reserve_percent"], money(a["budget_ask"]),
                      money(a["high"]), a["required_percent"]))
        out.append("")
        out.append("This is the single most likely way this estimate causes a "
                   "problem: not that the\npoint figure is wrong, but that the "
                   "contingency carried on top of it is too thin\nfor how wide "
                   "the real spread is.")
    out.append("")

    out.append("## Breakdown")
    out.append("")
    out.append("| Item | Size | Files | Unknowns | Turns | Estimate | Range | n |")
    out.append("| --- | --- | ---: | ---: | ---: | ---: | --- | ---: |")
    for row in result["items"]:
        out.append("| %s | %s%s | %d | %d | %s | %s | %s – %s | %d |"
                   % (row["name"], row["size"],
                      " (brownfield)" if row["brownfield"] else "",
                      row["files"], row["unknowns"],
                      format(row["turns"], ","), money(row["cost"]),
                      money(row["low"]), money(row["high"]), row["n"]))
    out.append("")
    if result.get("thin_buckets"):
        out.append("> **Thin calibration data.** These size classes have fewer "
                   "than 3 recorded\n> sessions behind them: **%s**. Their "
                   "medians are weak and the corresponding\n> figures above "
                   "should be treated as little better than a guess."
                   % ", ".join(result["thin_buckets"]))
        out.append("")

    out.append("## Calibration basis")
    out.append("")
    out.append(basis)
    out.append("")
    out.append("Cost per agent turn: **%s**. Rates are **list price** — an "
               "organization on\ncontracted rates must substitute its own."
               % money(p["cost_per_main_turn"]))
    out.append("")
    if result.get("corrections"):
        out.append("### Correction factors from recorded actuals")
        out.append("")
        out.append("| Bucket | n | Observed ratio | Applied (shrunk) | In effect |")
        out.append("| --- | ---: | ---: | ---: | --- |")
        for c in result["corrections"]:
            out.append("| %s | %d | %.2fx | %.2fx | %s |"
                       % (c["bucket"], c["n"], c["median_ratio"] or 1.0,
                          c["shrunk_ratio"], "yes" if c["applied"] else
                          "no — provisional"))
        out.append("")
        out.append("Observed ratios are shrunk toward 1.0 in proportion to "
                   "sample size, so a single\nrecorded actual cannot swing "
                   "future estimates.")
        out.append("")

    if result.get("licensing"):
        out.append(licensing.render_markdown(result["licensing"]))

    out.append("## Assumptions and sensitivities")
    out.append("")
    out.append("- Turn counts come from the calibration profile, and are the "
               "weakest input in\n  this model. Where `n` is small, treat the "
               "figure as indicative only.")
    out.append("- Cost scales with context size and turn count. Session "
               "hygiene — clearing between\n  unrelated tasks — moves the "
               "number more than most scope changes do.")
    out.append("- Brownfield work is scaled by %.1fx over greenfield."
               % 1.5)
    out.append("- Each declared unknown widens the upper bound by 25%.")
    out.append("")
    for warning in result.get("warnings") or []:
        out.append("> WARNING: %s" % warning)
    if result.get("warnings"):
        out.append("")

    out.append("## Known limits")
    out.append("")
    out.append("1. **Build only.** Says nothing about what the built thing "
               "costs to run.")
    out.append("2. **Turn counts are the weakest input**, and thin buckets are "
               "flagged above.")
    out.append("3. **List pricing only.** Contracted rates must be substituted.")
    out.append("4. **This machine only.** Sessions from other devices are not "
               "visible.")
    out.append("5. **Rates go stale.** Both providers change pricing without "
               "notice.")
    out.append("")
    out.append("## Close the loop")
    out.append("")
    out.append("When this build is done, record what it actually cost. That is "
               "how the estimator\ngets better — and without it, it cannot.")
    out.append("")
    out.append("```")
    out.append("python record_actual.py %s --sessions <session-id> [...]"
               % result["estimate_id"])
    out.append("```")
    out.append("")
    out.append("---")
    out.append("")
    out.append("*%s*" % FOOTER)
    out.append("")
    return "\n".join(out)


CSS = """
@page { size: Letter; margin: 0.85in 0.75in 1.0in 0.75in;
        @bottom-center { content: none; } }
* { box-sizing: border-box; }
body { font-family: "Charter","Bitstream Charter",Georgia,serif;
       font-size: 10.5pt; line-height: 1.55; color: #1a1a1a; margin: 0; }
h1 { font-family: "Helvetica Neue",Arial,sans-serif; font-size: 22pt;
     color: #1f3a5f; margin: 0 0 4px 0; }
h2 { font-family: "Helvetica Neue",Arial,sans-serif; font-size: 13.5pt;
     color: #1f3a5f; margin: 22px 0 8px 0; padding-bottom: 4px;
     border-bottom: 2px solid #d8e0ea; break-after: avoid; }
h3 { font-family: "Helvetica Neue",Arial,sans-serif; font-size: 11pt;
     color: #2c4a70; margin: 16px 0 6px 0; break-after: avoid; }
table { width: 100%; border-collapse: collapse; margin: 10px 0 14px 0;
        font-size: 9.5pt; break-inside: avoid; }
th { background: #eef2f7; text-align: left; padding: 6px 9px;
     border-bottom: 2px solid #c9d4e2; font-family: "Helvetica Neue",Arial,sans-serif;
     font-size: 8.5pt; text-transform: uppercase; letter-spacing: .04em; }
td { padding: 6px 9px; border-bottom: 1px solid #e6ebf1; vertical-align: top; }
blockquote { margin: 14px 0; padding: 12px 16px; background: #fdf6e6;
             border-left: 4px solid #d9a441; break-inside: avoid; }
blockquote h3 { margin-top: 0; color: #8a5d00; font-size: 10.5pt;
                letter-spacing: .03em; }
blockquote p { margin: 6px 0; font-size: 9.5pt; }
code { font-family: "SF Mono",Menlo,Consolas,monospace; font-size: 9pt;
       background: #f2f4f7; padding: 1px 4px; border-radius: 2px; }
pre { background: #f2f4f7; padding: 10px 12px; border-radius: 3px;
      font-size: 9pt; overflow-x: auto; }
.footer-note { margin-top: 26px; padding-top: 10px;
               border-top: 1px solid #d8e0ea; font-size: 8.5pt; color: #6b7683; }
"""

FOOTER_TEMPLATE = (
    '<div style="font-size:7pt;color:#8a8f98;width:100%;padding:0 0.75in;'
    'font-family:Helvetica,Arial,sans-serif;">'
    '<span style="float:left;">' + FOOTER + '</span>'
    '<span style="float:right;">'
    '<span class="pageNumber"></span> / <span class="totalPages"></span>'
    '</span></div>'
)


def write_pdf(md_text, pdf_path, title):
    """Render Markdown to PDF. Returns None on success, or a reason string."""
    try:
        import markdown as md_lib
    except ImportError:
        return ("the `markdown` package is not installed "
                "(pip install markdown)")
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return ("Playwright is not installed "
                "(pip install playwright && playwright install chromium)")

    body = md_lib.markdown(md_text, extensions=["tables", "fenced_code"])
    html = ("<!doctype html><html><head><meta charset='utf-8'>"
            "<title>%s</title><meta name='author' content='%s'>"
            "<style>%s</style></head><body>%s</body></html>"
            % (title, AUTHOR, CSS, body))

    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            try:
                page = browser.new_page()
                page.set_content(html, wait_until="load")
                page.pdf(path=pdf_path, format="Letter",
                         print_background=True,
                         display_header_footer=True,
                         header_template="<div></div>",
                         footer_template=FOOTER_TEMPLATE,
                         margin={"top": "0.7in", "bottom": "0.8in",
                                 "left": "0.75in", "right": "0.75in"})
            finally:
                browser.close()
    except Exception as exc:
        return "Chromium could not render the PDF (%s). Try: playwright install chromium" % exc
    return None


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("estimate_json")
    ap.add_argument("-o", "--out", default="build-work-estimate")
    ap.add_argument("--format", choices=["md", "pdf", "both"], default="both")
    ap.add_argument("--credits-json", default=None)
    args = ap.parse_args(argv)

    with open(args.estimate_json, "r") as fh:
        result = json.load(fh)
    credits = None
    if args.credits_json:
        with open(args.credits_json, "r") as fh:
            credits = json.load(fh)

    md_text = build_markdown(result, credits)
    written = []

    if args.format in ("md", "both"):
        md_path = args.out + ".md"
        with open(md_path, "w") as fh:
            fh.write(md_text)
        written.append(md_path)
        print("Wrote %s" % md_path)

    if args.format in ("pdf", "both"):
        if args.format == "pdf":
            # Always leave the Markdown behind: the estimate must survive a
            # PDF toolchain failure.
            md_path = args.out + ".md"
            with open(md_path, "w") as fh:
                fh.write(md_text)
            written.append(md_path)
        pdf_path = args.out + ".pdf"
        reason = write_pdf(md_text, pdf_path,
                           "Build Work Estimate - %s" % result["project"])
        if reason:
            print("WARNING  PDF not generated: %s" % reason)
            print("         The Markdown estimate at %s is complete."
                  % (args.out + ".md"))
            print("         On a host that creates documents natively "
                  "(Copilot Cowork, Claude Cowork,")
            print("         Copilot Studio), ask it to produce the PDF from "
                  "that Markdown rather")
            print("         than installing a browser.")
        else:
            written.append(pdf_path)
            print("Wrote %s" % pdf_path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
